spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/teletubbies?serverTimezone=Asia/Seoul
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#    hibernate:
#      ddl-auto: none
#      use-new-id-generator-mappings: false
#    properties:
#      hibernate:
#        globally_quoted_identifiers: true
